name: Run Automated Tests

on:
  pull_request:
    types: [opened, synchronize]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests for Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: run unittest
        run: |
          python -m unittest discover foalorm.orm.tests
